/**
 * Domain re-export: Hook system (32 events + matcher + JSON output).
 * Source of truth: ./official.d.ts.
 */
export type {
  HookEvent,
  HookInput,
  HookCallback,
  HookCallbackMatcher,
  HookJSONOutput,
  HookPermissionDecision,
  AsyncHookJSONOutput,
  SyncHookJSONOutput,
  BaseHookInput,

  PreToolUseHookInput,
  PreToolUseHookSpecificOutput,
  PostToolUseHookInput,
  PostToolUseHookSpecificOutput,
  PostToolUseFailureHookInput,
  PostToolUseFailureHookSpecificOutput,
  PostToolBatchHookInput,
  PostToolBatchHookSpecificOutput,
  PostToolBatchToolCall,
  PreCompactHookInput,
  PostCompactHookInput,
  NotificationHookInput,
  NotificationHookSpecificOutput,
  UserPromptSubmitHookInput,
  UserPromptSubmitHookSpecificOutput,
  UserPromptExpansionHookInput,
  UserPromptExpansionHookSpecificOutput,
  SessionStartHookInput,
  SessionStartHookSpecificOutput,
  SessionEndHookInput,
  StopHookInput,
  StopFailureHookInput,
  SubagentStartHookInput,
  SubagentStartHookSpecificOutput,
  SubagentStopHookInput,
  PermissionRequestHookInput,
  PermissionRequestHookSpecificOutput,
  PermissionDeniedHookInput,
  PermissionDeniedHookSpecificOutput,
  SetupHookInput,
  SetupHookSpecificOutput,
  TeammateIdleHookInput,
  TaskCreatedHookInput,
  TaskCompletedHookInput,
  ElicitationHookInput,
  ElicitationHookSpecificOutput,
  ElicitationResultHookInput,
  ElicitationResultHookSpecificOutput,
  ElicitationRequest,
  ElicitationResult,
  ConfigChangeHookInput,
  WorktreeCreateHookInput,
  WorktreeCreateHookSpecificOutput,
  WorktreeRemoveHookInput,
  InstructionsLoadedHookInput,
  CwdChangedHookInput,
  CwdChangedHookSpecificOutput,
  FileChangedHookInput,
  FileChangedHookSpecificOutput,

  OnElicitation,
} from './official.js'

export { HOOK_EVENTS } from './official-values.js'
