/**
 * Domain re-export: SDKMessage union and all 28 variants.
 * Source of truth: ./official.d.ts.
 */
export type {
  SDKMessage,
  SDKMessageOrigin,
  SDKAssistantMessage,
  SDKAssistantMessageError,
  SDKUserMessage,
  SDKUserMessageReplay,
  SDKResultMessage,
  SDKResultSuccess,
  SDKResultError,
  SDKSystemMessage,
  SDKPartialAssistantMessage,
  SDKCompactBoundaryMessage,
  SDKStatusMessage,
  SDKStatus,
  SDKAPIRetryMessage,
  SDKLocalCommandOutputMessage,
  SDKHookStartedMessage,
  SDKHookProgressMessage,
  SDKHookResponseMessage,
  SDKPluginInstallMessage,
  SDKToolProgressMessage,
  SDKAuthStatusMessage,
  SDKTaskNotificationMessage,
  SDKTaskStartedMessage,
  SDKTaskUpdatedMessage,
  SDKTaskProgressMessage,
  SDKSessionStateChangedMessage,
  SDKNotificationMessage,
  SDKFilesPersistedEvent,
  SDKToolUseSummaryMessage,
  SDKMemoryRecallMessage,
  SDKRateLimitEvent,
  SDKRateLimitInfo,
  SDKElicitationCompleteMessage,
  SDKPromptSuggestionMessage,
  SDKMirrorErrorMessage,
  SDKDeferredToolUse,
  SDKPermissionDenial,
  ModelUsage,
  NonNullableUsage,
} from './official.js'
